export enum LandingPageRoutes {
  Functionalities = "/funcionalidades",
  Plans = "/planos",
  Faq = "/faq",
  Help = "/ajuda",
  Suport = "/suporte",
  Terms = "/termos",
  Privacity = "/privacidade",
  AboutUs = "/sobre-nos",
  Contact = "/contato",
  SignIn = "/entrar",
  SignUp = "/cadastro",
  ForgotPassword = "/esqueceu-senha",
  ChangePassword = "/nova-senha",
}
